package apresentacao;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import negocio.Livro;
import persistencia.ILivroDAO;
import persistencia.LivroDAO;

/**
 *
 * @author Lelio Victor
 */
public class fmLivros extends javax.swing.JInternalFrame {
    private Livro livroSelecionado = null;

    /**
     * Creates new form fmLivros
     */
    public fmLivros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jLivros = new javax.swing.JTable();
        btAdicionar = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Gestão de livros");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Titulo", "Autor", "Editora", "Preço", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jLivros.setEditingColumn(0);
        jLivros.setEditingRow(0);
        jLivros.setFocusable(false);
        jLivros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLivrosMouseClicked(evt);
            }
        });
        jLivros.addPropertyChangeListener(this::jLivrosPropertyChange);
        jScrollPane1.setViewportView(jLivros);

        btAdicionar.setText("Adicionar");
        btAdicionar.addActionListener(this::btAdicionarActionPerformed);

        btEditar.setText("Editar");
        btEditar.setEnabled(false);
        btEditar.addActionListener(this::btEditarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(btEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(btAdicionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btEditar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        fmAdicionarLivro adicionarLivro = new fmAdicionarLivro(this.livroSelecionado, () -> reloadTable());
        adicionarLivro.setVisible(true);
    }//GEN-LAST:event_btEditarActionPerformed

    private void reloadTable() {
        ILivroDAO dao = new LivroDAO();
        List<Livro> livros = dao.listarTodos();
        
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Id");
        model.addColumn("Titulo");
        model.addColumn("Autor");
        model.addColumn("Editora");
        model.addColumn("Preço");
        model.addColumn("Quantidade");
        
        for(Livro livro: livros) {
            model.addRow(new Object[]{livro.getIdLivro(), livro.getTitulo(), livro.getAutor(), 
                livro.getEditora(), livro.getPreco(), livro.getQuantidade()});
        }
        
        jLivros.setModel(model);
    }
    
    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        reloadTable();
    }//GEN-LAST:event_formInternalFrameOpened

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        fmAdicionarLivro adicionarLivro = new fmAdicionarLivro(null, () -> reloadTable());
        adicionarLivro.setVisible(true);
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void jLivrosPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLivrosPropertyChange
    }//GEN-LAST:event_jLivrosPropertyChange

    private void jLivrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLivrosMouseClicked
        btEditar.setEnabled(true);
        
        int rowSelected = jLivros.getSelectedRow();
        
        if (rowSelected == -1) {
            return ;
        }
        
        int idLivro = Integer.parseInt(jLivros.getValueAt(rowSelected, 0).toString());
        String titulo = jLivros.getValueAt(rowSelected, 1).toString();
        String autor = jLivros.getValueAt(rowSelected, 2).toString();
        String editora = jLivros.getValueAt(rowSelected, 3).toString();
        double preco = Double.parseDouble(jLivros.getValueAt(rowSelected, 4).toString());
        int quantidade = Integer.parseInt(jLivros.getValueAt(rowSelected, 5).toString());
        
        this.livroSelecionado = new Livro(idLivro, titulo, autor, editora, preco, quantidade);
    }//GEN-LAST:event_jLivrosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btEditar;
    private javax.swing.JTable jLivros;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
